# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_TABS.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1308, 1077)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.home_tab)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_20 = QtWidgets.QFrame(self.home_tab)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_20)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_7.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.equalizer_plot = PlotWidget(self.frame_7)
        self.equalizer_plot.setObjectName("equalizer_plot")
        self.verticalLayout.addWidget(self.equalizer_plot)
        self.line_8 = QtWidgets.QFrame(self.frame_7)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.frame_13 = QtWidgets.QFrame(self.frame_7)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_16 = QtWidgets.QLabel(self.frame_13)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_13)
        self.gridLayout_14.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_20)
        self.frame_8.setMaximumSize(QtCore.QSize(10000, 200))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.line_6 = QtWidgets.QFrame(self.frame_8)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_7.addWidget(self.line_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.slider_label1 = QtWidgets.QLabel(self.frame_8)
        self.slider_label1.setObjectName("slider_label1")
        self.verticalLayout_6.addWidget(self.slider_label1)
        self.slider_label2 = QtWidgets.QLabel(self.frame_8)
        self.slider_label2.setObjectName("slider_label2")
        self.verticalLayout_6.addWidget(self.slider_label2)
        self.slider_label3 = QtWidgets.QLabel(self.frame_8)
        self.slider_label3.setObjectName("slider_label3")
        self.verticalLayout_6.addWidget(self.slider_label3)
        self.slider_label4 = QtWidgets.QLabel(self.frame_8)
        self.slider_label4.setObjectName("slider_label4")
        self.verticalLayout_6.addWidget(self.slider_label4)
        self.slider_label5 = QtWidgets.QLabel(self.frame_8)
        self.slider_label5.setObjectName("slider_label5")
        self.verticalLayout_6.addWidget(self.slider_label5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.slider1 = QtWidgets.QSlider(self.frame_8)
        self.slider1.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.horizontalLayout_6.addWidget(self.slider1)
        spacerItem2 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.slider2 = QtWidgets.QSlider(self.frame_8)
        self.slider2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.horizontalLayout_6.addWidget(self.slider2)
        spacerItem3 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.slider3 = QtWidgets.QSlider(self.frame_8)
        self.slider3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setObjectName("slider3")
        self.horizontalLayout_6.addWidget(self.slider3)
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.slider4 = QtWidgets.QSlider(self.frame_8)
        self.slider4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setObjectName("slider4")
        self.horizontalLayout_6.addWidget(self.slider4)
        spacerItem5 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.slider5 = QtWidgets.QSlider(self.frame_8)
        self.slider5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider5.setOrientation(QtCore.Qt.Vertical)
        self.slider5.setObjectName("slider5")
        self.horizontalLayout_6.addWidget(self.slider5)
        spacerItem6 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.slider6 = QtWidgets.QSlider(self.frame_8)
        self.slider6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider6.setOrientation(QtCore.Qt.Vertical)
        self.slider6.setObjectName("slider6")
        self.horizontalLayout_6.addWidget(self.slider6)
        spacerItem7 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.slider7 = QtWidgets.QSlider(self.frame_8)
        self.slider7.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider7.setOrientation(QtCore.Qt.Vertical)
        self.slider7.setObjectName("slider7")
        self.horizontalLayout_6.addWidget(self.slider7)
        spacerItem8 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.slider8 = QtWidgets.QSlider(self.frame_8)
        self.slider8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider8.setOrientation(QtCore.Qt.Vertical)
        self.slider8.setObjectName("slider8")
        self.horizontalLayout_6.addWidget(self.slider8)
        spacerItem9 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.slider9 = QtWidgets.QSlider(self.frame_8)
        self.slider9.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider9.setOrientation(QtCore.Qt.Vertical)
        self.slider9.setObjectName("slider9")
        self.horizontalLayout_6.addWidget(self.slider9)
        spacerItem10 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.slider10 = QtWidgets.QSlider(self.frame_8)
        self.slider10.setMaximumSize(QtCore.QSize(16777215, 200))
        self.slider10.setOrientation(QtCore.Qt.Vertical)
        self.slider10.setObjectName("slider10")
        self.horizontalLayout_6.addWidget(self.slider10)
        self.gridLayout_10.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_20)
        self.frame_9.setMaximumSize(QtCore.QSize(10000, 55))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line_7 = QtWidgets.QFrame(self.frame_9)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.freq1 = QtWidgets.QLabel(self.frame_9)
        self.freq1.setObjectName("freq1")
        self.horizontalLayout_8.addWidget(self.freq1)
        spacerItem11 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.freq2 = QtWidgets.QLabel(self.frame_9)
        self.freq2.setObjectName("freq2")
        self.horizontalLayout_8.addWidget(self.freq2)
        spacerItem12 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.freq3 = QtWidgets.QLabel(self.frame_9)
        self.freq3.setObjectName("freq3")
        self.horizontalLayout_8.addWidget(self.freq3)
        spacerItem13 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.freq4 = QtWidgets.QLabel(self.frame_9)
        self.freq4.setObjectName("freq4")
        self.horizontalLayout_8.addWidget(self.freq4)
        spacerItem14 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.freq5 = QtWidgets.QLabel(self.frame_9)
        self.freq5.setObjectName("freq5")
        self.horizontalLayout_8.addWidget(self.freq5)
        spacerItem15 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.freq6 = QtWidgets.QLabel(self.frame_9)
        self.freq6.setObjectName("freq6")
        self.horizontalLayout_8.addWidget(self.freq6)
        spacerItem16 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.freq7 = QtWidgets.QLabel(self.frame_9)
        self.freq7.setObjectName("freq7")
        self.horizontalLayout_8.addWidget(self.freq7)
        spacerItem17 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.freq8 = QtWidgets.QLabel(self.frame_9)
        self.freq8.setObjectName("freq8")
        self.horizontalLayout_8.addWidget(self.freq8)
        spacerItem18 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem18)
        self.freq9 = QtWidgets.QLabel(self.frame_9)
        self.freq9.setObjectName("freq9")
        self.horizontalLayout_8.addWidget(self.freq9)
        spacerItem19 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.freq10 = QtWidgets.QLabel(self.frame_9)
        self.freq10.setObjectName("freq10")
        self.horizontalLayout_8.addWidget(self.freq10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.gridLayout_11.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.frame_20)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_19 = QtWidgets.QFrame(self.frame_12)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.save_result_button = QtWidgets.QPushButton(self.frame_19)
        self.save_result_button.setObjectName("save_result_button")
        self.gridLayout_15.addWidget(self.save_result_button, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_19)
        self.frame_6 = QtWidgets.QFrame(self.frame_12)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        self.show_result_button = QtWidgets.QPushButton(self.frame_6)
        self.show_result_button.setObjectName("show_result_button")
        self.gridLayout.addWidget(self.show_result_button, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.frame_12)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.reset_button_home = QtWidgets.QPushButton(self.frame)
        self.reset_button_home.setObjectName("reset_button_home")
        self.gridLayout_7.addWidget(self.reset_button_home, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem21 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem21)
        self.frame_10 = QtWidgets.QFrame(self.frame_12)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.play_button_home = QtWidgets.QPushButton(self.frame_10)
        self.play_button_home.setMinimumSize(QtCore.QSize(50, 50))
        self.play_button_home.setObjectName("play_button_home")
        self.gridLayout_13.addWidget(self.play_button_home, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_10)
        spacerItem22 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.label_32 = QtWidgets.QLabel(self.frame_12)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_2.addWidget(self.label_32)
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.frame_11 = QtWidgets.QFrame(self.frame_12)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.comboBox = QtWidgets.QComboBox(self.frame_11)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_12.addWidget(self.comboBox, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.gridLayout_16.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_20, 0, 0, 1, 1)
        self.tabWidget.addTab(self.home_tab, "")
        self.signals_tab = QtWidgets.QWidget()
        self.signals_tab.setObjectName("signals_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.signals_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.signals_tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_time_plot = PlotWidget(self.frame_4)
        self.input_time_plot.setMinimumSize(QtCore.QSize(0, 175))
        self.input_time_plot.setObjectName("input_time_plot")
        self.verticalLayout_3.addWidget(self.input_time_plot)
        self.line_3 = QtWidgets.QFrame(self.frame_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        spacerItem24 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem24)
        self.input_fourier_plot = PlotWidget(self.frame_4)
        self.input_fourier_plot.setMinimumSize(QtCore.QSize(0, 175))
        self.input_fourier_plot.setObjectName("input_fourier_plot")
        self.verticalLayout_3.addWidget(self.input_fourier_plot)
        self.line_5 = QtWidgets.QFrame(self.frame_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        spacerItem25 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem25)
        self.output_time_plot = PlotWidget(self.frame_4)
        self.output_time_plot.setMinimumSize(QtCore.QSize(0, 175))
        self.output_time_plot.setObjectName("output_time_plot")
        self.verticalLayout_3.addWidget(self.output_time_plot)
        self.line_9 = QtWidgets.QFrame(self.frame_4)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_3.addWidget(self.line_9)
        spacerItem26 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem26)
        self.output_fourier_plot = PlotWidget(self.frame_4)
        self.output_fourier_plot.setMinimumSize(QtCore.QSize(0, 175))
        self.output_fourier_plot.setObjectName("output_fourier_plot")
        self.verticalLayout_3.addWidget(self.output_fourier_plot)
        self.line_10 = QtWidgets.QFrame(self.frame_4)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_3.addWidget(self.line_10)
        spacerItem27 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem27)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem28)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.play_button_signals = QtWidgets.QPushButton(self.frame_5)
        self.play_button_signals.setObjectName("play_button_signals")
        self.gridLayout_4.addWidget(self.play_button_signals, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem29)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.signals_tab, "")
        self.gridLayout_26.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1308, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Open = QtWidgets.QAction(MainWindow)
        self.Open.setObjectName("Open")
        self.Save = QtWidgets.QAction(MainWindow)
        self.Save.setObjectName("Save")
        self.menuFile.addAction(self.Open)
        self.menuFile.addAction(self.Save)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "Equalizer"))
        self.slider_label1.setText(_translate("MainWindow", " 10"))
        self.slider_label2.setText(_translate("MainWindow", " 5"))
        self.slider_label3.setText(_translate("MainWindow", " 0"))
        self.slider_label4.setText(_translate("MainWindow", "- 5"))
        self.slider_label5.setText(_translate("MainWindow", " -10"))
        self.freq1.setText(_translate("MainWindow", "110 Hz"))
        self.freq2.setText(_translate("MainWindow", "2 KHz"))
        self.freq3.setText(_translate("MainWindow", "4 KHz"))
        self.freq4.setText(_translate("MainWindow", "6 KHz"))
        self.freq5.setText(_translate("MainWindow", "8 KHz"))
        self.freq6.setText(_translate("MainWindow", "10 KHz"))
        self.freq7.setText(_translate("MainWindow", "12 KHz"))
        self.freq8.setText(_translate("MainWindow", "14 KHz"))
        self.freq9.setText(_translate("MainWindow", "16 KHz"))
        self.freq10.setText(_translate("MainWindow", "20 KHz"))
        self.save_result_button.setText(_translate("MainWindow", "Save Result"))
        self.show_result_button.setText(_translate("MainWindow", "Compare Results"))
        self.reset_button_home.setText(_translate("MainWindow", "Reset"))
        self.play_button_home.setText(_translate("MainWindow", "Play"))
        self.label_32.setText(_translate("MainWindow", "Filters:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Hamming"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hanning"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.play_button_signals.setText(_translate("MainWindow", "Play"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signals_tab), _translate("MainWindow", "Signals"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Open.setText(_translate("MainWindow", "Open"))
        self.Open.setStatusTip(_translate("MainWindow", "open file"))
        self.Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.Save.setStatusTip(_translate("MainWindow", "save file"))
        self.Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
